steps:
  - name: gcr.io/cloud-builders/docker
    script: |
      echo "Hello this is a ${DOCKER_USERNAME}"
      echo $DOCKER_USERNAME && echo $$DOCKER_USERNAME
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      echo $SHORT_SHA
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
options:
  dynamic_substitutions: true
  env:
    - 'JPETSTOREWEB=DOCKER_USERNAME/jpetstoreweb'
substitutions:
  _DOCKER_USERNAME: DOCKER_USERNAME
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest'
      env: 'DOCKER_USERNAME'
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest'
      env: 'DOCKER_PASSWORD'
