steps:
  - name: gcr.io/cloud-builders/docker
    script: |
      echo "Hello this is a ${_DOCKER_USERNAME}"
      echo $_DOCKER_USERNAME && echo $$_DOCKER_USERNAME
      docker login -u $_DOCKER_USERNAME -p $_DOCKER_PASSWORD
      echo "PROJECT ID is ${PROJECT_ID}"
      echo "RANDOM ${RANDOM}"
    env:
      - 'JPETSTOREWEB=${_DOCKER_USERNAME}/jpetstoreweb'
      - 'BUILD=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'PROJECT_NUMBER=$PROJECT_NUMBER'
      - 'REV=$REVISION_ID'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'RANDOM=${_DOCKER_USERNAME}'
    secretEnv: ['_DOCKER_USERNAME', '_DOCKER_PASSWORD']
options:
  dynamic_substitutions: true
# substitutions:
#   _DOCKER_USERNAME: $DOCKER_USERNAME
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest'
      env: '_DOCKER_USERNAME'
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest'
      env: '_DOCKER_PASSWORD'
