steps:
  - name: ubuntu
    script: |
      #!/bin/bash
      echo "Hello World"
      echo "Testing cloud build"
      echo $JPETSTOREWEB
      echo $$DOCKER_USERNAME
    # env:
    #   - 'JPETSTOREWEB=$${DOCKER_USERNAME}/jpetstoreweb'
    # secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
    secretEnv:
      - 'JPETSTOREWEB=$$DOCKER_USERNAME/jpetstoreweb'
      - 'DOCKER_USERNAME'
      - 'DOCKER_PASSWORD'
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest
      env: 'DOCKER_USERNAME'
    - versionName: projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest
      env: 'DOCKER_PASSWORD'
