steps:
  - name: ubuntu
    script: |
      #!/bin/bash
      echo "Hello World"
      echo "Testing cloud build"
      echo $$DOCKER_USERNAME
    env:
      - 'JPETSTOREWEB=$$DOCKER_USERNAME/jpetstoreweb'
availableSecrets:
  secretManager:
    - versionName: projects/PROJECT_ID/secrets/DOCKER_USERNAME/versions/latest
      env: 'DOCKER_USERNAME'
    - versionName: projects/PROJECT_ID/secrets/DOCKER_PASSWORD/versions/latest
      env: 'DOCKER_PASSWORD'
