steps:
  - name: bash
    args: ['-c', 'echo $$DOCKER_USERNAME']
    # script: |
    #   echo "Hello World"
    #   echo "Testing cloud build"
    #   echo $JPETSTOREWEB
    #   echo $$DOCKER_USERNAME
    #   docker login "https://index.docker.io/v1" -u=$$DOCKER_USERNAME -p=$$DOCKER_PASSWORD
    # env:
    #   - 'JPETSTOREWEB=$${DOCKER_USERNAME}/jpetstoreweb'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest'
      env: 'DOCKER_USERNAME'
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest'
      env: 'DOCKER_PASSWORD'
