steps:
  - name: gcr.io/cloud-builders/docker
    id: 'Build Application'
    script: |
      export TIMESTAMP=`date -u +%Y%m%d%H%M%S`
      echo "BUILD_TAG ${DOCKER_USERNAME}/jpetstoreweb:${BUILD_TAG}-${TIMESTAMP}"
      docker build -t "${DOCKER_USERNAME}/jpetstoreweb:${BUILD_TAG}-${TIMESTAMP}" -t "${DOCKER_USERNAME}/jpetstoreweb:latest" ./jpetstore
      docker build -t "${DOCKER_USERNAME}/jpetstoredb:${BUILD_TAG}-${TIMESTAMP}" -t "${DOCKER_USERNAME}/jpetstoredb:latest" .
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker push "${DOCKER_USERNAME}/jpetstoreweb:${BUILD_TAG}-${TIMESTAMP}"
      docker push "${DOCKER_USERNAME}/jpetstoreweb:latest"
      docker push "${DOCKER_USERNAME}/jpetstoredb:${BUILD_TAG}-${TIMESTAMP}"
      docker push "${DOCKER_USERNAME}/jpetstoredb:latest"
    env:
      - 'BUILD_TAG=${BUILD_ID}-${BRANCH_NAME}-${SHORT_SHA}'
      - 'JPETSTOREWEB=${_DOCKER_USERNAME}/jpetstoreweb'
      - 'BUILD=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'PROJECT_NUMBER=$PROJECT_NUMBER'
      - 'REV=$REVISION_ID'
      - 'SHORT_SHA=$SHORT_SHA'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
  - name: openjdk:19-jdk-alpine3.16
    id: 'Test application'
    script: |
      java --version
      apk update && apk add apache-ant
      cd jpetstore
      ls
      ant runtest
      cd ..
      cp -r ./jpetstore/build/reports/TEST-*.xml /workspace/
  - name: 'gcr.io/$PROJECT_ID/helm'
    id: 'Deploy application'
    # args: ['install', 'stable/keel', '--name', 'keel', '--namespace', 'keel']
    script: |
      helm --version
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=petstore-gke-cluster'
options:
  dynamic_substitutions: true
substitutions:
  _DOCKER_USERNAME: $DOCKER_USERNAME
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest'
      env: 'DOCKER_USERNAME'
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest'
      env: 'DOCKER_PASSWORD'
