steps:
  - name: gcr.io/cloud-builders/docker
    script: |
      export TIMESTAMP=`date -u +%Y%m%d%H%M%S`
      echo "BUILD_TAG ${DOCKER_USERNAME}/jpetstoreweb:${BUILD_TAG}-${TIMESTAMP}"
      docker build -t "${DOCKER_USERNAME}/jpetstoreweb:${BUILD_TAG}-${TIMESTAMP}" -t "${DOCKER_USERNAME}/jpetstoreweb:latest" ./jpetstore
      docker build -t "${DOCKER_USERNAME}/jpetstoredb:${BUILD_TAG}-${TIMESTAMP}" -t "${DOCKER_USERNAME}/jpetstoredb:latest" .
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker push "${DOCKER_USERNAME}/jpetstoreweb:${BUILD_TAG}-${TIMESTAMP}"
      docker push "${DOCKER_USERNAME}/jpetstoreweb:latest"
      docker push "${DOCKER_USERNAME}/jpetstoredb:${BUILD_TAG}-${TIMESTAMP}""
      docker push "${DOCKER_USERNAME}/jpetstoredb:latest"
    env:
      - 'BUILD_TAG=${BUILD_ID}-${BRANCH_NAME}-${SHORT_SHA}'
      - 'JPETSTOREWEB=${_DOCKER_USERNAME}/jpetstoreweb'
      - 'BUILD=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'PROJECT_NUMBER=$PROJECT_NUMBER'
      - 'REV=$REVISION_ID'
      - 'SHORT_SHA=$SHORT_SHA'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
options:
  dynamic_substitutions: true
substitutions:
  _DOCKER_USERNAME: $DOCKER_USERNAME
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest'
      env: 'DOCKER_USERNAME'
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest'
      env: 'DOCKER_PASSWORD'
