steps:
  - name: gcr.io/cloud-builders/docker
    script: |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      echo "This is the Build Tag ${BUILD_TAG}"
      echo "URL ${JPETSTOREDB}"
    env:
      - 'BUILD_TAG=${BUILD_ID}-${REPO_NAME}-${SHORT_SHA}'
      - 'JPETSTOREWEB=${_DOCKER_USERNAME}/jpetstoreweb'
      - 'BUILD=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'PROJECT_NUMBER=$PROJECT_NUMBER'
      - 'REV=$REVISION_ID'
      - 'SHORT_SHA=$SHORT_SHA'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
options:
  dynamic_substitutions: true
substitutions:
  _DOCKER_USERNAME: hello
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest'
      env: 'DOCKER_USERNAME'
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest'
      env: 'DOCKER_PASSWORD'
