steps:
  - name: gcr.io/cloud-builders/docker
    script: |
      echo "Hello this is a ${DOCKER_USERNAME}"
      echo $DOCKER_USERNAME && echo $$DOCKER_USERNAME
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      echo $_IMAGE_NAME
    env:
      - 'JPETSTOREWEB=$_DOCKER_USERNAME/jpetstoreweb'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
substitutions:
  _IMAGE_NAME: '${DOCKER_USERNAME}/test-image'
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_USERNAME/versions/latest'
      env: 'DOCKER_USERNAME'
    - versionName: 'projects/${PROJECT_ID}/secrets/DOCKER_PASSWORD/versions/latest'
      env: 'DOCKER_PASSWORD'
